package omoikane.formularios;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.image.*;
import java.util.*;

import omoikane.principal.Principal;
import omoikane.producto.Impuesto;
import omoikane.producto.departamento.Departamento;
import omoikane.repository.DepartamentoRepo;
import omoikane.sistema.*;

/*
 * @author Octavio
 */
public class Articulo extends javax.swing.JInternalFrame {

    BufferedImage fondo;
    public int ID;

    /**
     * Creates new form Articulo
     */
    public Articulo() {
        initComponents();
        //Instrucciones para el funcionamiento del fondo semistransparente
        this.setOpaque(false);
        ((JPanel) this.getContentPane()).setOpaque(false);
        this.getLayeredPane().setOpaque(false);
        this.getRootPane().setOpaque(false);
        this.generarFondo(this);

        Herramientas.centrarVentana(this);

        loadDepartamentos();
    }

    private void loadDepartamentos() {
        DepartamentoRepo repo = (DepartamentoRepo) Principal.applicationContext.getBean("departamentoRepo");
        Departamento depNull = new Departamento(){{
            setId(null);
            setNombre("Sin clasificar");
        }};

        java.util.List<Departamento> departamentos = repo.findAllActive();
        comboDepartamento.addItem(depNull);
        for (Departamento departamento : departamentos)
            comboDepartamento.addItem(departamento);
    }

    private ArrayList<Impuesto> loadTiposImpuestos() {
        EntityManagerFactory emf = (EntityManagerFactory) Principal.applicationContext.getBean("entityManagerFactory");
        EntityManager em = emf.createEntityManager();
        ArrayList<Impuesto> impuestoList = (ArrayList<Impuesto>) em.createQuery("SELECT im FROM Impuesto im", Impuesto.class).getResultList();
        return impuestoList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        tabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIDArticulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIDGrupoDes = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUnidad = new javax.swing.JComboBox();
        txtPrecio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUModificacion = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        txtIDGrupo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtIDLinea = new javax.swing.JTextField();
        txtIDLineaDes = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        setComboDepartamento(new JComboBox());
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtUtilidad = new javax.swing.JTextField();
        txtDescuento2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JFormattedTextField();
        txtPrecioTotal = new javax.swing.JFormattedTextField();
        txtDesctoPorcentaje = new javax.swing.JFormattedTextField();
        txtUtilidadPorc = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        impuestosTable = new javax.swing.JTable();
        btnQuitarImpuesto = new javax.swing.JButton();
        btnAgregarImpuesto = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtComentarios = new javax.swing.JTextArea();

        setTitle("Producto");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<html><head><style type='text/css'>body { font-family: 'Roboto Thin'; font-size: 28px; }</style></head> <body> Art&iacute;culo </body></html>"); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 80, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 80, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 100, -1));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 10, 10));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("<html>ID Art&iacute;culo:</html>");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        txtIDArticulo.setEditable(false);
        txtIDArticulo.setBackground(new java.awt.Color(51, 51, 51));
        txtIDArticulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtIDArticulo.setForeground(new java.awt.Color(255, 255, 255));
        txtIDArticulo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIDArticulo.setBorder(null);
        txtIDArticulo.setFocusable(false);
        jPanel1.add(txtIDArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 340, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("<html>C&oacute;digo <br>principal:<html>");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 30));

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 51, 340, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("<html>ID L&iacute;nea [F1]:</html>");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, 30));

        txtIDGrupoDes.setEditable(false);
        txtIDGrupoDes.setBackground(new java.awt.Color(51, 51, 51));
        txtIDGrupoDes.setForeground(new java.awt.Color(255, 255, 255));
        txtIDGrupoDes.setBorder(null);
        txtIDGrupoDes.setFocusable(false);
        jPanel1.add(txtIDGrupoDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 290, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("<html>Descripci&oacute;n:</html>");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 90, 30));

        txtDescripcion.setEditable(false);
        txtDescripcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 340, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Unidad:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 90, 30));

        txtUnidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtUnidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PZA", "CAJA", "PAQ", "KG", "LT" }));
        txtUnidad.setEnabled(false);
        jPanel1.add(txtUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 340, 30));

        txtPrecio.setEditable(false);
        txtPrecio.setBackground(new java.awt.Color(51, 51, 51));
        txtPrecio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPrecio.setText("0.0");
        txtPrecio.setBorder(null);
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 340, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Precio:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("<html>&Uacute;ltima<br>Modificaci&oacute;n:</html>");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        txtUModificacion.setEditable(false);
        txtUModificacion.setBackground(new java.awt.Color(51, 51, 51));
        txtUModificacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtUModificacion.setForeground(new java.awt.Color(255, 255, 255));
        txtUModificacion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtUModificacion.setText("Sin fecha");
        txtUModificacion.setBorder(null);
        txtUModificacion.setFocusable(false);
        jPanel1.add(txtUModificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 340, 30));
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -40, -1, 20));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Descuento:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 30));

        txtDescuento.setEditable(false);
        txtDescuento.setBackground(new java.awt.Color(51, 51, 51));
        txtDescuento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtDescuento.setForeground(new java.awt.Color(255, 255, 255));
        txtDescuento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDescuento.setText("0.0");
        txtDescuento.setBorder(null);
        jPanel1.add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 340, 30));

        txtIDGrupo.setEditable(false);
        txtIDGrupo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtIDGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDGrupoActionPerformed(evt);
            }
        });
        jPanel1.add(txtIDGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 40, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Departamento:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 90, 30));

        txtIDLinea.setEditable(false);
        txtIDLinea.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtIDLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 40, 30));

        txtIDLineaDes.setEditable(false);
        txtIDLineaDes.setBackground(new java.awt.Color(51, 51, 51));
        txtIDLineaDes.setForeground(new java.awt.Color(255, 255, 255));
        txtIDLineaDes.setBorder(null);
        txtIDLineaDes.setFocusable(false);
        jPanel1.add(txtIDLineaDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 290, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("ID Grupo [F1] :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 30));

        jPanel1.add(getComboDepartamento(), new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 340, 30));

        tabbedPane.addTab("<html>General</html>", jPanel1);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Costo:");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, 30));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Utilidad (%):");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Detalles del precio y costo");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Precio:");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("$");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 20, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("$");
        jLabel21.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 20, 30));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("$:");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, 20));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("$:");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, 20));

        txtUtilidad.setEditable(false);
        txtUtilidad.setBackground(new java.awt.Color(51, 51, 51));
        txtUtilidad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUtilidad.setForeground(new java.awt.Color(255, 255, 255));
        txtUtilidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUtilidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtUtilidad.setFocusable(false);
        jPanel5.add(txtUtilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 120, 30));

        txtDescuento2.setEditable(false);
        txtDescuento2.setBackground(new java.awt.Color(51, 51, 51));
        txtDescuento2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDescuento2.setForeground(new java.awt.Color(255, 255, 255));
        txtDescuento2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDescuento2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtDescuento2.setFocusable(false);
        jPanel5.add(txtDescuento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 120, 30));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("el precio siguiente no incluye los demas descuentos");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 340, 20));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Descuento (%):");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, 20));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("<html>Nota: El descuento que aparece es solo por art&iacute;culo  </html>");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 340, 20));

        txtCosto.setEditable(false);
        txtCosto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtCosto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCosto.setToolTipText("Solo números");
        txtCosto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCosto.setHighlighter(null);
        txtCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCostoKeyReleased(evt);
            }
        });
        jPanel5.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 140, 30));

        comboDepartamento.setEditable(false);

        txtPrecioTotal.setEditable(false);
        txtPrecioTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtPrecioTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrecioTotal.setToolTipText("Solo números");
        txtPrecioTotal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPrecioTotal.setHighlighter(null);
        txtPrecioTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecioTotalKeyReleased(evt);
            }
        });
        jPanel5.add(txtPrecioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 140, 30));

        txtDesctoPorcentaje.setEditable(false);
        txtDesctoPorcentaje.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtDesctoPorcentaje.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDesctoPorcentaje.setToolTipText("Solo numeros");
        txtDesctoPorcentaje.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDesctoPorcentaje.setHighlighter(null);
        txtDesctoPorcentaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDesctoPorcentajeKeyReleased(evt);
            }
        });
        jPanel5.add(txtDesctoPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 110, 30));

        txtUtilidadPorc.setEditable(false);
        txtUtilidadPorc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtUtilidadPorc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUtilidadPorc.setToolTipText("Solo numeros");
        txtUtilidadPorc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUtilidadPorc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUtilidadPorcKeyReleased(evt);
            }
        });
        jPanel5.add(txtUtilidadPorc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 110, 30));

        impuestosTable.setModel(new ImpuestosTableModel(
            new Object [][] {

            },
            new String [] {
                "Impuesto", "Porcentaje", "Importe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        impuestosTable.setFocusable(false);
        jScrollPane1.setViewportView(impuestosTable);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 350, 80));

        btnQuitarImpuesto.setText(" - ");
        btnQuitarImpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarImpuestoActionPerformed(evt);
            }
        });
        jPanel5.add(btnQuitarImpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 50, 20));

        btnAgregarImpuesto.setText(" + ");
        btnAgregarImpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarImpuestoActionPerformed(evt);
            }
        });
        jPanel5.add(btnAgregarImpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 60, 20));

        tabbedPane.addTab("<html>Precio</html>", jPanel5);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jScrollPane4.setMaximumSize(new java.awt.Dimension(32767, 200));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(406, 383));
        jScrollPane4.setViewportView(txtComentarios);

        txtComentarios.setColumns(25);
        txtComentarios.setRows(20);
        txtComentarios.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        txtComentarios.setPreferredSize(null);
        jScrollPane4.setViewportView(txtComentarios);

        jPanel7.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        tabbedPane.addTab("<html>Notas</html>", jPanel7);

        getContentPane().add(tabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 480, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_btnCerrarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        omoikane.principal.Articulos.guardar(this);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        omoikane.principal.Articulos.modificar(this);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtPrecioTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioTotalKeyReleased
        // TODO add your handling code here:
        omoikane.principal.Articulos.recalcularUtilidad(this);
}//GEN-LAST:event_txtPrecioTotalKeyReleased

    private void txtDesctoPorcentajeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDesctoPorcentajeKeyReleased
        // TODO add your handling code here:
        omoikane.principal.Articulos.recalcularCampos(this);
    }//GEN-LAST:event_txtDesctoPorcentajeKeyReleased

    private void txtUtilidadPorcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUtilidadPorcKeyReleased
        // TODO add your handling code here:
        omoikane.principal.Articulos.recalcularCampos(this);
    }//GEN-LAST:event_txtUtilidadPorcKeyReleased

    private void txtCostoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostoKeyReleased
        // TODO add your handling code here:
        omoikane.principal.Articulos.recalcularCampos(this);
    }//GEN-LAST:event_txtCostoKeyReleased

    private void txtIDGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDGrupoActionPerformed

    private void btnAgregarImpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarImpuestoActionPerformed
        Object[] impuestos = loadTiposImpuestos().toArray();
        Impuesto impuesto = (Impuesto) JOptionPane.showInputDialog(this, "Selecciona un impuesto", "Impuestos", JOptionPane.QUESTION_MESSAGE,
                null, impuestos, null);
        if(!((ImpuestosTableModel)getImpuestosTable().getModel()).exists( impuesto ))
        {
            Object[] row = {impuesto};
            ((DefaultTableModel)getImpuestosTable().getModel()).addRow(row);
            omoikane.principal.Articulos.recalcularCampos(this);
        }
    }//GEN-LAST:event_btnAgregarImpuestoActionPerformed

    private void btnQuitarImpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarImpuestoActionPerformed
        int row = getImpuestosTable().getSelectedRow();
        if(row >= 0) {
            ((DefaultTableModel)getImpuestosTable().getModel()).removeRow(row);
            ((DefaultTableModel)getImpuestosTable().getModel()).fireTableDataChanged();
            omoikane.principal.Articulos.recalcularCampos(this);
        }
    }//GEN-LAST:event_btnQuitarImpuestoActionPerformed

    public void setEditable(boolean editable) {
        //this.tblCodigos.setEnabled(editable);
        this.txtCodigo.setEditable(editable);
        this.txtComentarios.setEditable(editable);
        this.txtCosto.setEditable(editable);
        this.txtDescripcion.setEditable(editable);
        this.txtDesctoPorcentaje.setEditable(editable);
        this.txtDescuento2.setEditable(editable);
        this.txtIDGrupo.setEditable(editable);
        this.txtIDLinea.setEditable(editable);
        this.txtPrecioTotal.setEditable(editable);
        this.txtUnidad.setEnabled(editable);
        this.comboDepartamento.setEnabled(editable);
        this.txtUtilidad.setEditable(editable);
        this.txtUtilidadPorc.setEditable(editable);

    }

    public void setModoDetalles() {
        setModo(Modos.DETALLES);
        setEditable(false);
        this.btnGuardar.setVisible(false);
        this.btnModificar.setVisible(false);

    }

    public void setModoModificar() {
        setModo(Modos.MODIFICAR);
        setEditable(true);
        this.btnGuardar.setVisible(false);
        this.btnModificar.setVisible(true);
    }

    public void setModoNuevo() {
        setModo(Modos.NUEVO);
        setEditable(true);
        this.btnModificar.setVisible(false);
    }

    public JTable getImpuestosTable() {
        return impuestosTable;
    }

    public JComboBox getComboDepartamento() {
        return comboDepartamento;
    }

    public void setComboDepartamento(JComboBox comboDepartamento) {
        this.comboDepartamento = comboDepartamento;
    }

    public enum Modos {

        NUEVO, DETALLES, MODIFICAR
    };
    private Modos modo;

    private void setModo(Modos m) {
        modo = m;
    }

    public Modos getModo() {
        return modo;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarImpuesto;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnQuitarImpuesto;
    private javax.swing.JComboBox<Departamento> comboDepartamento;
    private javax.swing.JTable impuestosTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtComentarios;
    private javax.swing.JFormattedTextField txtCosto;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JFormattedTextField txtDesctoPorcentaje;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtDescuento2;
    private javax.swing.JTextField txtIDArticulo;
    public javax.swing.JTextField txtIDGrupo;
    public javax.swing.JTextField txtIDGrupoDes;
    public javax.swing.JTextField txtIDLinea;
    public javax.swing.JTextField txtIDLineaDes;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JFormattedTextField txtPrecioTotal;
    private javax.swing.JTextField txtUModificacion;
    private javax.swing.JComboBox txtUnidad;
    private javax.swing.JTextField txtUtilidad;
    private javax.swing.JFormattedTextField txtUtilidadPorc;
    // End of variables declaration//GEN-END:variables

    public String getTxtCodigo() {
        return txtCodigo.getText();
    }

    public String getTxtDescripcion() {
        return txtDescripcion.getText();
    }

    public String getTxtIDArticulo() {
        return txtIDArticulo.getText();
    }

    public String getTxtUnidad() {
        return String.valueOf(txtUnidad.getSelectedItem());
    }

    public String getTxtUModificacion() {
        return txtUModificacion.getText();
    }

    public String getTxtIDLinea() {
        return txtIDLinea.getText();
    }

    public String getTxtIDGrupo() {
        return txtIDGrupo.getText();
    }

    public String getTxtDescuento() {
        return txtDescuento.getText();
    }

    public String getTxtCosto() {
        return txtCosto.getText();
    }

    public String getTxtPrecio() {
        return txtPrecio.getText();
    }

    public String getTxtComentarios() {
        return txtComentarios.getText();
    }

    public Component getIDLinea() {
        return txtIDLinea;
    }

    public Component getIDGrupo() {
        return txtIDGrupo;
    }


    public JTextField getCampoID() {
        return txtIDLinea;
    }

    public JTextField getCampoGrupo() {
        return txtIDGrupo;
    }

    public JTextField getTxtDesctoPorcentaje() {
        return txtDesctoPorcentaje;
    }

    public JTextField getTxtDescuento2() {
        return txtDescuento2;
    }

    public JTextField getTxtPrecioTotal() {
        return txtPrecioTotal;
    }

    public JTextField getTxtUtilidadPorc() {
        return txtUtilidadPorc;
    }

    public JTextField getTxtUtilidad() {
        return txtUtilidad;
    }

    public void setTxtCodigo(String txtCodigo) {
        this.txtCodigo.setText(txtCodigo);
    }

    public void setTxtDescripcion(String txtDescripcion) {
        this.txtDescripcion.setText(txtDescripcion);
    }

    public void setTxtIDArticulo(String txtIDArticulo) {
        this.txtIDArticulo.setText(txtIDArticulo);
    }

    public void setTxtUnidad(String txt) {
        this.txtUnidad.setSelectedItem(txt);
    }

    public void setTxtUModificacion(String txt) {
        txtUModificacion.setText(txt);
    }

    public void setTxtIDLinea(String IDLinea) {
        txtIDLinea.setText(IDLinea);
    }

    public void setTxtIDGrupo(String IDGrupo) {
        txtIDGrupo.setText(IDGrupo);
    }

    public void setTxtIDLineaDes(String IDLinea) {
        txtIDLineaDes.setText(IDLinea);
    }

    public void setTxtIDGrupoDes(String IDGrupo) {
        txtIDGrupoDes.setText(IDGrupo);
    }

    public void setTxtDescuento(String descuento) {
        txtDescuento.setText(descuento);
    }

    public void setTxtCosto(String costo) {
        txtCosto.setText(costo);
    }

    public void setTxtPrecio(String precio) {
        this.txtPrecio.setText(precio);
    }

    public void setTxtPrecioTotal(String precio) {
        this.txtPrecioTotal.setText(precio);
    }

    public void setTxtImpuestos(String txt) {
        this.getTxtPrecioTotal().setText(txt);
    }

    public void setTxtDesctoPorcentaje(String txtDestoPorcentaje) {
        this.txtDesctoPorcentaje.setText(txtDestoPorcentaje);
    }

    public void setTxtDescuento2(javax.swing.JTextField txtDescuento2) {
        this.txtDescuento2 = txtDescuento2;
    }

    public void setTxtDescuento3(String descuento) {
        this.txtDescuento2.setText(descuento);
    }

    public void setTxtUtilidadPorc(String txtUtilidadPorc) {
        this.txtUtilidadPorc.setText(txtUtilidadPorc);
    }

    public void setTxtUtilidadPorcText(String txt) {
        txtUtilidadPorc.setText(txt);
    }

    public void setTxtUtilidad(javax.swing.JTextField txtUtilidad) {
        this.txtUtilidad = txtUtilidad;
    }

    public void setTxtUtilidad2(String utilidad) {
        this.txtUtilidad.setText(utilidad);
    }

    public void setTxtComentarios(String text) {
        txtComentarios.setText(text);
    }

    public void paintComponent(Graphics g) {
        Graphics2D g2d = (Graphics2D) g;
        g2d.drawImage(fondo, 0, 0, null);

    }

    public void generarFondo(Component componente) {
        Rectangle areaDibujo = this.getBounds();
        BufferedImage tmp;
        GraphicsConfiguration gc = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDefaultConfiguration();

        tmp = gc.createCompatibleImage(areaDibujo.width, areaDibujo.height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) tmp.getGraphics();
        g2d.setColor(new Color(0,0,0,165));
        g2d.fillRect(0, 0, areaDibujo.width, areaDibujo.height);
        fondo = tmp;
    }
}

/*
 costo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                costoCaretUpdate(evt);
            }
        });
*/